Upgrades to the latest Ember CLI
ember-cli/ember-cli-legacy-blueprints pull request #79
Opened 2017-01-11 15:16 UTC by twokul

2017-01-11 15:24 UTC, Turbo87 commented on LICENSE.md
> +Copyright (c) 2017
this should be `2015-2017`

2017-01-11 15:24 UTC, Turbo87 commented on .travis.yml
> +  - "5"
we should probably test against `4, 6, stable` at this point

2017-01-11 16:19 UTC, twokul commented on LICENSE.md
> +Copyright (c) 2017
this should likely be fixed in the default blueprint?

2017-01-11 16:25 UTC, Turbo87 commented on LICENSE.md
> +Copyright (c) 2017
how would you fix that? it depends on the project that you're using `ember init` on.

2017-01-11 16:26 UTC, Turbo87 approved these changes

2017-01-11 17:45 UTC, nathanhammond requested changes
These may be upstream issues...

2017-01-11 17:45 UTC, nathanhammond commented on .travis.yml
> +  - "stable"
Mild preference for calling this `7` since https://github.com/creationix/nvm/blob/f1a5f2a15fd2867a4a5762b80cae028d324ee6a1/README.markdown#L182

2017-01-11 17:45 UTC, nathanhammond commented on package.json
> +    "node": ">= 4"
`4 || 6 || 7` ... 5 isn't supported.

2018-11-24 21:52 UTC, Turbo87 commented
closing due to inactivity and open merge conflicts. I guess we should probably archive this whole project as it's no longer needed.

2018-11-24 21:52 UTC, closed without merging